// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrkwHE-9sjP3_rGRSd343NvSqdF_cyXEE',
    appId: '1:575765744893:web:3ec415c547774c7379c294',
    messagingSenderId: '575765744893',
    projectId: 'final-chat-app-f404e',
    authDomain: 'final-chat-app-f404e.firebaseapp.com',
    storageBucket: 'final-chat-app-f404e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmJDi_gRpEOFYAontlxdV9t8td-e3SkNI',
    appId: '1:575765744893:android:1b97ff16e44f4d3679c294',
    messagingSenderId: '575765744893',
    projectId: 'final-chat-app-f404e',
    storageBucket: 'final-chat-app-f404e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb78vwOoNLrll3TYqumPbU867IRwa0BX4',
    appId: '1:575765744893:ios:81efb5c60a93c7a379c294',
    messagingSenderId: '575765744893',
    projectId: 'final-chat-app-f404e',
    storageBucket: 'final-chat-app-f404e.appspot.com',
    iosClientId: '575765744893-g04lpfjeke3ihhmsfbl0sj82jnmckroo.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb78vwOoNLrll3TYqumPbU867IRwa0BX4',
    appId: '1:575765744893:ios:81efb5c60a93c7a379c294',
    messagingSenderId: '575765744893',
    projectId: 'final-chat-app-f404e',
    storageBucket: 'final-chat-app-f404e.appspot.com',
    iosClientId: '575765744893-g04lpfjeke3ihhmsfbl0sj82jnmckroo.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalChatApp',
  );
}
