// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClA-gGRw5EBZsay24f6QKCekaNEkXvMRk',
    appId: '1:993564859486:web:fc9d1fbe97ae1b0a9928cf',
    messagingSenderId: '993564859486',
    projectId: 'material-chat-ac507',
    authDomain: 'material-chat-ac507.firebaseapp.com',
    storageBucket: 'material-chat-ac507.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkNbn9yy1_aHcMeqkaxAJ-zQoSFNZs--Y',
    appId: '1:993564859486:android:6171baae0b1fe6929928cf',
    messagingSenderId: '993564859486',
    projectId: 'material-chat-ac507',
    storageBucket: 'material-chat-ac507.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABeogO4UKnYykZBQkCcMNWKxKcOXYmUck',
    appId: '1:993564859486:ios:080d6131a0ab04689928cf',
    messagingSenderId: '993564859486',
    projectId: 'material-chat-ac507',
    storageBucket: 'material-chat-ac507.appspot.com',
    iosClientId: '993564859486-vk0vpiut2fbqs4sq4da2j9v03vqdlheb.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABeogO4UKnYykZBQkCcMNWKxKcOXYmUck',
    appId: '1:993564859486:ios:080d6131a0ab04689928cf',
    messagingSenderId: '993564859486',
    projectId: 'material-chat-ac507',
    storageBucket: 'material-chat-ac507.appspot.com',
    iosClientId: '993564859486-vk0vpiut2fbqs4sq4da2j9v03vqdlheb.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalChatApp',
  );
}
